name: Gitflow release
on:
  push:
    branches:
      - release
  pull_request_review:
    branches:
      - release
  check_run:
    types:
      - completed

jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
    - uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
        dev: develop # The `dev` branch.
